default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: bh168058
  host: localhost

development:
  <<: *default
  database: appdevelop

test:
  <<: *default
  database: apptest

production:
  <<: *default
  database: appprod
